/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.geolix;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int LinearLayout01=0x7f040007;
        public static final int RelativeLayout01=0x7f040000;
        public static final int TextView01=0x7f040001;
        public static final int TextView02=0x7f040003;
        public static final int TextView03=0x7f040005;
        public static final int adresse=0x7f04000b;
        public static final int afficherAdresse=0x7f04000a;
        public static final int altitude=0x7f040006;
        public static final int choix_source=0x7f040008;
        public static final int latitude=0x7f040002;
        public static final int longitude=0x7f040004;
        public static final int obtenir_position=0x7f040009;
    }
    public static final class layout {
        public static final int geoposition=0x7f020000;
        public static final int main=0x7f020001;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
